/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermarketmanagement;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class SignUp extends javax.swing.JFrame {

    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        confirm_password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jButton_signup = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_mail = new javax.swing.JTextField();
        jButton_login = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(255, 102, 102), new java.awt.Color(0, 153, 153), new java.awt.Color(255, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 18, 59));
        jLabel1.setText("Fresh deals ahead!");

        jLabel2.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Sign up now and start saving! ");

        jLabel_close.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 102, 102));
        jLabel_close.setText("  X");
        jLabel_close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jLabel_minimize.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(255, 102, 102));
        jLabel_minimize.setText("  -");
        jLabel_minimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 18, 59));
        jLabel6.setText("name");

        jTextField_username.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_username.setText("username");
        jTextField_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 18, 59));
        jLabel7.setText("Confirm Password");

        confirm_password.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        confirm_password.setForeground(new java.awt.Color(204, 204, 204));
        confirm_password.setText("password");
        confirm_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        confirm_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirm_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirm_passwordFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 18, 59));
        jLabel8.setText("password");

        jPasswordField_password.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPasswordField_password.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField_password.setText("password");
        jPasswordField_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jPasswordField_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_passwordFocusLost(evt);
            }
        });

        jButton_signup.setBackground(new java.awt.Color(4, 59, 92));
        jButton_signup.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_signup.setForeground(new java.awt.Color(255, 255, 255));
        jButton_signup.setText("Sign up");
        jButton_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_signupActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 18, 59));
        jLabel3.setText("E-mail");

        jTextField_mail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField_mail.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_mail.setText("Mail");
        jTextField_mail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jTextField_mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_mailFocusLost(evt);
            }
        });

        jButton_login.setBackground(new java.awt.Color(4, 59, 92));
        jButton_login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_login.setText("Sign in");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 18, 59));
        jLabel9.setText("username");

        jTextField_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField_name.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_name.setText("name");
        jTextField_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jTextField_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_nameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordField_password, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(confirm_password, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_username, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_mail)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_login)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_signup))
                                .addComponent(jTextField_name, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.decode("#006666"));
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.decode("#006666"));
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.decode("#FF6666"));
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.decode("#FF6666"));
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.decode("#006666"));
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.decode("#006666"));
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.decode("#FF6666"));
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.decode("#FF6666"));
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        // TODO add your handling code here:
        // clear the textfield on focus if the text is "username"
        if (jTextField_username.getText().trim().toLowerCase().equals("username"));
        {
            jTextField_username.setText("");
            jTextField_username.setForeground(Color.decode("#2F4F4F"));
        }
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusLost
        // TODO add your handling code here:
        if (jTextField_username.getText().trim().equals("")
                || jTextField_username.getText().trim().toLowerCase().equals("username")) {
            jTextField_username.setText("username");
            jTextField_username.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jTextField_usernameFocusLost

    private void confirm_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_passwordFocusGained
        // TODO add your handling code here:
        String pass = String.valueOf(confirm_password.getPassword());
        if (pass.trim().toLowerCase().equals("password"));
        {
            confirm_password.setText("");  // user input
            confirm_password.setForeground(Color.decode("#2F4F4F"));
        }
    }//GEN-LAST:event_confirm_passwordFocusGained

    private void confirm_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_passwordFocusLost
        // TODO add your handling code here:
        String pass = String.valueOf(confirm_password.getPassword());
        if (pass.trim().equals("")
                || pass.trim().toLowerCase().equals("password")) {
            confirm_password.setText("password");
            confirm_password.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_confirm_passwordFocusLost

    private void jPasswordField_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passwordFocusGained
        // TODO add your handling code here:
        String pass1 = String.valueOf(jPasswordField_password.getPassword());
        if (pass1.trim().toLowerCase().equals("password"));
        {
            jPasswordField_password.setText("");  // user input
            jPasswordField_password.setForeground(Color.decode("#2F4F4F"));
        }
    }//GEN-LAST:event_jPasswordField_passwordFocusGained

    private void jPasswordField_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passwordFocusLost
        // TODO add your handling code here:
        String pass1 = String.valueOf(jPasswordField_password.getPassword());
        if (pass1.trim().equals("")
                || pass1.trim().toLowerCase().equals("password")) {
            jPasswordField_password.setText("password");
            jPasswordField_password.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jPasswordField_passwordFocusLost

    private void jTextField_mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_mailFocusGained
        // TODO add your handling code here:
        if (jTextField_mail.getText().trim().toLowerCase().equals("mail"));
        {
            jTextField_mail.setText("");
            jTextField_mail.setForeground(Color.decode("#2F4F4F"));
        }
    }//GEN-LAST:event_jTextField_mailFocusGained

    private void jTextField_mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_mailFocusLost
        // TODO add your handling code here:
        if (jTextField_mail.getText().trim().equals("")
                || jTextField_mail.getText().trim().toLowerCase().equals("mail")) {
            jTextField_mail.setText("mail");
            jTextField_mail.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jTextField_mailFocusLost

    private void jButton_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_signupActionPerformed

        String name = jTextField_name.getText();
        String user_name = jTextField_username.getText();
        String mail = jTextField_mail.getText();
        String pass1 = String.valueOf(jPasswordField_password.getPassword());
        String pass2 = String.valueOf(confirm_password.getPassword());

        if (emptyFields()) {
            if (!checkUserName(user_name)) {
                PreparedStatement st;
                ResultSet rs;
                String signUpUserQuery = "INSERT INTO supermarket_login.sign_up_info ( name,username, E_mail, password) VALUES (?,?,?,?)";

                try {

                    st = DatabaseConnection.getConnection().prepareStatement(signUpUserQuery);

                    st.setString(1, name);
                    st.setString(2, user_name);
                    st.setString(3, mail);
                    st.setString(4, pass1);

                    //rs = st.executeQuery();
                    if (st.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Your account has been successfully created!");

                        HomePage home = new HomePage();
                        home.setVisible(true);
                        home.pack();
                        home.setLocationRelativeTo(null);
                        home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        // Close the current login form
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, " Something Went Wrong!");
                    }

                } catch (SQLException ex) {
                    // Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton_signupActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed

        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jTextField_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nameFocusGained
        // TODO add your handling code here:
        if (jTextField_name.getText().trim().toLowerCase().equals("name"));
        {
            jTextField_name.setText("");
            jTextField_name.setForeground(Color.decode("#2F4F4F"));
        }
    }//GEN-LAST:event_jTextField_nameFocusGained

    private void jTextField_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nameFocusLost
        // TODO add your handling code here:
        if (jTextField_name.getText().trim().equals("")
                || jTextField_name.getText().trim().toLowerCase().equals("name")) {
            jTextField_name.setText("mail");
            jTextField_name.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_jTextField_nameFocusLost

    // function to verify empty field
    public boolean emptyFields() {

        String name = jTextField_name.getText();
        String user_name = jTextField_username.getText();
        String mail = jTextField_mail.getText();
        String pass1 = String.valueOf(jPasswordField_password.getPassword());
        String pass2 = String.valueOf(confirm_password.getPassword());

        //chech empty fields
        if (name.trim().equals("") || user_name.trim().equals("") || user_name.trim().equals("") || mail.trim().equals("")
                || pass1.trim().equals("") || pass2.trim().equals("") || !mail.matches(emailPattern)) {
            JOptionPane.showMessageDialog(null, "Please fill in the empty box to help us stock up on your information!");
            return false;
        }

        if (pass1.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters!");
        }

        if (pass1.length() > 32) {
            JOptionPane.showMessageDialog(null, "Password must be less than 32 characters!");
        }

        // if 2 password not matched
        if (!pass1.equals(pass2)) {
            JOptionPane.showMessageDialog(null, "Oops! Passwords: mismatched", "Confirm Password", 2);
            return false;
        } else {
            return true;
        }
    }

    // function to check if the username already exists or not
    public boolean checkUserName(String username) {

        PreparedStatement st;
        ResultSet rs;
        boolean is_username = false;

        String query = "SELECT * FROM supermarket_login.sign_up_info WHERE username = ?";

        try {

            st = DatabaseConnection.getConnection().prepareStatement(query);

            st.setString(1, username);
            rs = st.executeQuery();

            if (rs.next()) {
                is_username = true;
                JOptionPane.showMessageDialog(null, "Username's taken!", "Try a different username, please!", 2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }

        return is_username;
    }

    public static ArrayList<User> getUserRecords() {
        ArrayList<User> list = new ArrayList<>();
        PreparedStatement st;
        ResultSet rs;

        String query = "SELECT * FROM supermarket_login.sign_up_info";
        try {
            st = DatabaseConnection.getConnection().prepareStatement(query);
            // st.setString(1, username);

            rs = st.executeQuery();
            while (rs.next()) {
                User user = new User();
                user.setId(rs.getInt("id"));
                user.setFullName(rs.getString("name"));
                user.setUserName(rs.getString("username"));
                user.setEmail(rs.getString("E_mail"));
                user.setStatus(rs.getString("user_status"));

                list.add(user);

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        return list;
    }

    public static void changeStatus(String username, String status) {
        PreparedStatement st;
        ResultSet rs;

        String query = "UPDATE supermarket_login.sign_up_info SET user_status = ? WHERE username = ?";
        try {
            st = DatabaseConnection.getConnection().prepareStatement(query);
            st.setString(1, status); // Set the status parameter
            st.setString(2, username); // Set the username parameter

            // Execute the update
            int rowsUpdated = st.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("User status updated successfully!");
            } else {
                System.out.println("No user found with the given username.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirm_password;
    private javax.swing.JButton jButton_login;
    private javax.swing.JButton jButton_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_mail;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
